### ISSUE TITLE
سوال؟

### ISSUE THREAD

**Issue by mimsadAlef** [rastikerdar/fontservice#1]
سلام
یه سوال
آیا برای تبدیل فونت ها داخل سرور اون پکیجی که نوشتید کافیه
من می تونم چنین سرویس فونتی رو بسازم فقط کمی وقت نیاز دارم
اگه میشه یکم کمکم کنید تا خدمتی به جامعه اوپن سورس بکنم

**Comment by rastikerdar** [comment]
سلام و درود
بلی کل پروسه بیلد با همین اسکریپت‌ها انجام میشه. اما روش های دیگری هم هست. مثلا برای ادغام دو تا فونت از اسکریپت پایمرج هم میشه استفاده کرد.

اما در کل من پیشنهاد نمی‌کنم چون:
- این ایده قدیمیه (چهار سال پیش) و با اومدن تکنولوژی فونت‌های وریبل (متغیر) و احتمالا رایج شدن اون در آینده نه چندان دور، حالت‌های مختلفی رو میشه در خود فونت گنجاند.
- فکر نمی‌کنم این روزها هنوز هم نیازی به خروجی‌های گفته شده وجود داشته باشه و به نظر درصد مخاطبان نسخه‌های خاص و غیر استاندارد زیاد نیست. اون موقعی که من این ایده رو نوشتم هنوز بازار فونت پر محصول نبود و اوایلش بود و تقاضا برای حالت‌های مختلف این چند فونت آزادی که ساختم زیاد بود اما تو این چند سال شرایط کاملا عوض شد.
- از منظر حقوقی فکر نمی‌کنم تغییر فونت‌ها کار قانونی‌ای باشه و البته هیچ سازنده فونتی (آزاد و غیز آزاد) اجازه تغییر یا ایجاد نسخه‌های متفاوت از محصولش رو نمی‌ده (که خب قابل دفاع و منطقیه) و حتی احتمال شکایت از سرویس هم وجود داره. یعنی این سرویس شاید در نهایت محدود بشه به همین چند تا فونتی که من ساختم که اغلبشون دیگه توسعه داده نمیشن.
- به دلیل گسترش نسخه‌های متعدد و غیر استاندارد، در بازار فونت ممکنه اخلال ایجاد کنه و آشفتگی به وجود بیاره.
